---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nodeops.node.io
  resources:
  - nodetaintrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodeops.node.io
  resources:
  - nodetaintrules/finalizers
  verbs:
  - update
- apiGroups:
  - nodeops.node.io
  resources:
  - nodetaintrules/status
  verbs:
  - get
  - patch
  - update
